spring:
  jpa:
    generate-ddl: true
  h2:
    console:
      enabled: true

server:
  servlet:
    context-path: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  profiles: postgres
  datasource:
    url: "jdbc:postgresql://localhost/clashofclans"
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          lob:
            non_contextual_creation: true